-------------------- Log Start | Tue Apr  2 07:06:16 2024 --------------------
data_path: /home/Pi/printer_data
is_default_data_path: False
config_file: /home/Pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: ed66581bdb9442a8ba66cabe74f1bd44
unix_socket_path: /home/Pi/printer_data/comms/moonraker.sock
software_version: v0.8.0-186-g2641fc5
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/Pi/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager]
refresh_interval = 168
enable_auto_refresh = True

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

[update_manager sonar]
type = git_repo
path = ~/sonar
origin = https://github.com/mainsail-crew/sonar.git
primary_branch = main
managed_services = sonar
install_script = tools/install.sh

[update_manager klipper-macros]
type = git_repo
origin = https://github.com/jschuh/klipper-macros.git
path = ~/printer_data/config/klipper-macros
primary_branch = main
is_system_service = False
managed_services = klipper

#################################################################
All Configuration Files:
/home/Pi/printer_data/config/moonraker.conf
#################################################################
Unsafe Shutdown Count: 15

System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 32bit
  processor: aarch64
  cpu_desc: 
  serial_number: 100000008ec46bbe
  hardware_desc: BCM2835
  model: Raspberry Pi 4 Model B Rev 1.5
  total_memory: 1713732
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SC32G
  product_revision: 8.0
  serial_number: 59bac505
  manufacturer_date: 7/2022
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Raspbian GNU/Linux 11 (bullseye)
  id: raspbian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: debian
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.2.1', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'network-online.target', 'sysinit.target']
**After=['sysinit.target', 'basic.target', 'klipper.service', 'system.slice', 'network-online.target', 'systemd-journald.socket']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/Pi/printer_data/systemd/moonraker.env
**ExecStart=/home/Pi/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=Pi

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', '-.mount']
**After=['sysinit.target', '-.mount', 'basic.target', 'system.slice', 'network-online.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/Pi/printer_data/systemd/klipper.env
**ExecStart=/home/Pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/Pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=Pi
Git Repo moonraker: Warnings detected:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
Git Repo klipper: Warnings detected:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
Git Repo mainsail-config: No warnings detected
Git Repo sonar: No warnings detected
Git Repo klipper-macros: No warnings detected
Klipper Version: v0.11.0-303-g67499853-dirty
2024-04-02 03:06:16,238 [base_deploy.py:log_info()] - PackageKit: Detected 46 package updates:
base-files
bind9-host
bind9-libs
bluez
bluez-firmware
cifs-utils
curl
distro-info-data
firmware-atheros
firmware-brcm80211
firmware-libertas
firmware-misc-nonfree
firmware-realtek
libbluetooth3
libc-bin
libc-dev-bin
libc-devtools
libc-l10n
libc6
libc6-dbg
libc6-dev
libcurl3-gnutls
libcurl4
libglib2.0-0
libglib2.0-bin
libglib2.0-data
libgnutls30
libjs-jquery-ui
libnftables1
libnghttp2-14
libperl5.32
libssh-gcrypt-4
libtiff5
libwbclient0
libzmq5
locales
nftables
openssh-client
openssh-server
openssh-sftp-server
perl
perl-base
perl-modules-5.32
ssh
tar
tzdata
2024-04-02 03:06:16,333 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker status --porcelain -b) successfully finished
2024-04-02 03:06:16,353 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker branch --list --no-color) successfully finished
2024-04-02 03:06:16,373 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker remote get-url origin) successfully finished
2024-04-02 03:06:16,807 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker fetch origin --prune --progress) successfully finished
2024-04-02 03:06:16,825 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker merge-base --is-ancestor HEAD origin/master) successfully finished
2024-04-02 03:06:16,837 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker rev-parse HEAD) successfully finished
2024-04-02 03:06:16,854 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker describe --always --tags --long --dirty --abbrev=8) successfully finished
2024-04-02 03:06:16,865 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker rev-parse origin/master) successfully finished
2024-04-02 03:06:16,887 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker describe origin/master --always --tags --long --abbrev=8) successfully finished
2024-04-02 03:06:16,904 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker rev-list HEAD..a3e4dac5fb20f8dfc0857a252eef5219d5e0ec4c --count) successfully finished
2024-04-02 03:06:16,924 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker log 2641fc54d6932445e54d3c2f72a74e46aaf290cf..origin/master --format="sha:%H%x1Dauthor:%an%x1Ddate:%ct%x1Dsubject:%s%x1Dmessage:%b%x1E" --max-count=100) successfully finished
2024-04-02 03:06:17,036 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/moonraker for-each-ref --count=100 --sort='-creatordate' --contains=HEAD --merged=origin/master --format='%(if)%(*objecttype)%(then)%(*objecttype) %(*objectname)%(else)%(objecttype) %(objectname)%(end) %(refname)' 'refs/tags') successfully finished
2024-04-02 03:06:17,038 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/Pi/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: 2641fc54d6932445e54d3c2f72a74e46aaf290cf
Upstream Commit SHA: a3e4dac5fb20f8dfc0857a252eef5219d5e0ec4c
Current Version: v0.8.0-186-g2641fc54
Upstream Version: v0.8.0-324-ga3e4dac5
Rollback Commit: 2641fc54d6932445e54d3c2f72a74e46aaf290cf
Rollback Branch: master
Rollback Version: v0.8.0-186-g2641fc5
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 138
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
2024-04-02 03:06:17,038 [base_deploy.py:log_info()] - Git Repo moonraker: Channel: dev
2024-04-02 03:06:17,038 [base_deploy.py:log_info()] - Git Repo moonraker: Validity check for git repo passed
2024-04-02 03:06:17,677 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper status --porcelain -b) successfully finished
2024-04-02 03:06:17,698 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper branch --list --no-color) successfully finished
2024-04-02 03:06:17,718 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper remote get-url origin) successfully finished
2024-04-02 03:06:18,456 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper fetch origin --prune --progress) successfully finished
2024-04-02 03:06:18,471 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper merge-base --is-ancestor HEAD origin/master) successfully finished
2024-04-02 03:06:18,481 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper rev-parse HEAD) successfully finished
2024-04-02 03:06:18,580 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper describe --always --tags --long --dirty --abbrev=8) successfully finished
2024-04-02 03:06:18,591 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper rev-parse origin/master) successfully finished
2024-04-02 03:06:18,682 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper describe origin/master --always --tags --long --abbrev=8) successfully finished
2024-04-02 03:06:18,700 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper rev-list HEAD..e37b007f67e5bdc330af45b78643f7789c789907 --count) successfully finished
2024-04-02 03:06:18,724 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper log 6749985302fe002a9cb5672dab9badb11e4e3c36..origin/master --format="sha:%H%x1Dauthor:%an%x1Ddate:%ct%x1Dsubject:%s%x1Dmessage:%b%x1E" --max-count=100) successfully finished
2024-04-02 03:06:18,862 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/klipper for-each-ref --count=100 --sort='-creatordate' --contains=HEAD --merged=origin/master --format='%(if)%(*objecttype)%(then)%(*objecttype) %(*objectname)%(else)%(objecttype) %(objectname)%(end) %(refname)' 'refs/tags') successfully finished
2024-04-02 03:06:18,863 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/Pi/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: 6749985302fe002a9cb5672dab9badb11e4e3c36
Upstream Commit SHA: e37b007f67e5bdc330af45b78643f7789c789907
Current Version: v0.11.0-303-g67499853
Upstream Version: v0.12.0-132-ge37b007f
Rollback Commit: 6749985302fe002a9cb5672dab9badb11e4e3c36
Rollback Branch: master
Rollback Version: v0.11.0-303-g67499853
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 142
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
2024-04-02 03:06:18,863 [base_deploy.py:log_info()] - Git Repo klipper: Channel: dev
2024-04-02 03:06:18,863 [base_deploy.py:log_info()] - Git Repo klipper: Validity check for git repo passed
2024-04-02 03:06:19,103 [web_deploy.py:_log_client_info()] - Web Client mainsail Detected:
Repo: mainsail-crew/mainsail
Channel: stable
Path: /home/Pi/mainsail
Local Version: v2.8.0
Remote Version: v2.10.0
Valid: True
Fallback Client Detected: False
Pre-release: False
Download Url: https://github.com/mainsail-crew/mainsail/releases/download/v2.10.0/mainsail.zip
Download Size: 2081565
Content Type: application/zip
Rollback Version: v2.8.0
Rollback Repo: mainsail-crew/mainsail
2024-04-02 03:06:19,136 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config status --porcelain -b) successfully finished
2024-04-02 03:06:19,157 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config branch --list --no-color) successfully finished
2024-04-02 03:06:19,176 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config remote get-url origin) successfully finished
2024-04-02 03:06:19,599 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config fetch origin --prune --progress) successfully finished
2024-04-02 03:06:19,610 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config merge-base --is-ancestor HEAD origin/master) successfully finished
2024-04-02 03:06:19,621 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config rev-parse HEAD) successfully finished
2024-04-02 03:06:19,634 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config describe --always --tags --long --dirty --abbrev=8) successfully finished
2024-04-02 03:06:19,645 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config rev-parse origin/master) successfully finished
2024-04-02 03:06:19,656 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config describe origin/master --always --tags --long --abbrev=8) successfully finished
2024-04-02 03:06:19,669 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config rev-list HEAD..e57810d51b5c634aadaca4db923bfcba269ae4b3 --count) successfully finished
2024-04-02 03:06:19,681 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config log c64d3af97a277ffdf607a398cc838991bcda069b..origin/master --format="sha:%H%x1Dauthor:%an%x1Ddate:%ct%x1Dsubject:%s%x1Dmessage:%b%x1E" --max-count=100) successfully finished
2024-04-02 03:06:19,695 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/mainsail-config for-each-ref --count=100 --sort='-creatordate' --contains=HEAD --merged=origin/master --format='%(if)%(*objecttype)%(then)%(*objecttype) %(*objectname)%(else)%(objecttype) %(objectname)%(end) %(refname)' 'refs/tags') successfully finished
2024-04-02 03:06:19,696 [git_deploy.py:log_repo_info()] - Git Repo mainsail-config Detected:
Owner: mainsail-crew
Repository Name: mainsail-config
Path: /home/Pi/mainsail-config
Remote: origin
Branch: master
Remote URL: https://github.com/mainsail-crew/mainsail-config.git
Recovery URL: https://github.com/mainsail-crew/mainsail-config.git
Current Commit SHA: c64d3af97a277ffdf607a398cc838991bcda069b
Upstream Commit SHA: e57810d51b5c634aadaca4db923bfcba269ae4b3
Current Version: v1.0.0-16-gc64d3af9
Upstream Version: v1.2.1-0-ge57810d5
Rollback Commit: c64d3af97a277ffdf607a398cc838991bcda069b
Rollback Branch: master
Rollback Version: v1.0.0-16-gc64d3af
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 3
Diverged: False
2024-04-02 03:06:19,696 [base_deploy.py:log_info()] - Git Repo mainsail-config: Channel: dev
2024-04-02 03:06:19,696 [base_deploy.py:log_info()] - Git Repo mainsail-config: Validity check for git repo passed
2024-04-02 03:06:19,721 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar status --porcelain -b) successfully finished
2024-04-02 03:06:19,741 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar branch --list --no-color) successfully finished
2024-04-02 03:06:19,761 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar remote get-url origin) successfully finished
2024-04-02 03:06:20,190 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar fetch origin --prune --progress) successfully finished
2024-04-02 03:06:20,202 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar merge-base --is-ancestor HEAD origin/main) successfully finished
2024-04-02 03:06:20,212 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar rev-parse HEAD) successfully finished
2024-04-02 03:06:20,224 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar describe --always --tags --long --dirty --abbrev=8) successfully finished
2024-04-02 03:06:20,235 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar rev-parse origin/main) successfully finished
2024-04-02 03:06:20,247 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar describe origin/main --always --tags --long --abbrev=8) successfully finished
2024-04-02 03:06:20,258 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar rev-list HEAD..eacc498a52f79292063b6f9b0e0c191c34c5dc09 --count) successfully finished
2024-04-02 03:06:20,272 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar log 7962a1225ad88fa2a642ae2b378637491b4b2710..origin/main --format="sha:%H%x1Dauthor:%an%x1Ddate:%ct%x1Dsubject:%s%x1Dmessage:%b%x1E" --max-count=100) successfully finished
2024-04-02 03:06:20,290 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/sonar for-each-ref --count=100 --sort='-creatordate' --contains=HEAD --merged=origin/main --format='%(if)%(*objecttype)%(then)%(*objecttype) %(*objectname)%(else)%(objecttype) %(objectname)%(end) %(refname)' 'refs/tags') successfully finished
2024-04-02 03:06:20,291 [git_deploy.py:log_repo_info()] - Git Repo sonar Detected:
Owner: mainsail-crew
Repository Name: sonar
Path: /home/Pi/sonar
Remote: origin
Branch: main
Remote URL: https://github.com/mainsail-crew/sonar.git
Recovery URL: https://github.com/mainsail-crew/sonar.git
Current Commit SHA: 7962a1225ad88fa2a642ae2b378637491b4b2710
Upstream Commit SHA: eacc498a52f79292063b6f9b0e0c191c34c5dc09
Current Version: v0.1.2-0-g7962a122
Upstream Version: v0.1.3-1-geacc498a
Rollback Commit: 7962a1225ad88fa2a642ae2b378637491b4b2710
Rollback Branch: main
Rollback Version: v0.1.2-0-g7962a12
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 3
Diverged: False
2024-04-02 03:06:20,291 [base_deploy.py:log_info()] - Git Repo sonar: Channel: dev
2024-04-02 03:06:20,291 [base_deploy.py:log_info()] - Git Repo sonar: Validity check for git repo passed
2024-04-02 03:06:20,322 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros status --porcelain -b) successfully finished
2024-04-02 03:06:20,343 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros branch --list --no-color) successfully finished
2024-04-02 03:06:20,363 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros remote get-url origin) successfully finished
2024-04-02 03:06:20,937 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros fetch origin --prune --progress) successfully finished
2024-04-02 03:06:20,950 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros merge-base --is-ancestor HEAD origin/main) successfully finished
2024-04-02 03:06:20,961 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros rev-parse HEAD) successfully finished
2024-04-02 03:06:20,973 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros describe --always --tags --long --dirty --abbrev=8) successfully finished
2024-04-02 03:06:20,984 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros rev-parse origin/main) successfully finished
2024-04-02 03:06:20,996 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros describe origin/main --always --tags --long --abbrev=8) successfully finished
2024-04-02 03:06:21,008 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros rev-list HEAD..ebae0a3b6ec4bf7096e7b068967b283992078f5f --count) successfully finished
2024-04-02 03:06:21,021 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros log 01c0d8aa06b39576501faaf9c905fae37d8aaef0..origin/main --format="sha:%H%x1Dauthor:%an%x1Ddate:%ct%x1Dsubject:%s%x1Dmessage:%b%x1E" --max-count=100) successfully finished
2024-04-02 03:06:21,040 [shell_command.py:_check_proc_success()] - Command (git -C /home/Pi/printer_data/config/klipper-macros for-each-ref --count=100 --sort='-creatordate' --contains=HEAD --merged=origin/main --format='%(if)%(*objecttype)%(then)%(*objecttype) %(*objectname)%(else)%(objecttype) %(objectname)%(end) %(refname)' 'refs/tags') successfully finished
2024-04-02 03:06:21,040 [git_deploy.py:log_repo_info()] - Git Repo klipper-macros Detected:
Owner: jschuh
Repository Name: klipper-macros
Path: /home/Pi/printer_data/config/klipper-macros
Remote: origin
Branch: main
Remote URL: https://github.com/jschuh/klipper-macros.git
Recovery URL: https://github.com/jschuh/klipper-macros.git
Current Commit SHA: 01c0d8aa06b39576501faaf9c905fae37d8aaef0
Upstream Commit SHA: ebae0a3b6ec4bf7096e7b068967b283992078f5f
Current Version: v0.8.7-0-g01c0d8aa
Upstream Version: v0.8.9-0-gebae0a3b
Rollback Commit: 01c0d8aa06b39576501faaf9c905fae37d8aaef0
Rollback Branch: main
Rollback Version: v0.8.7-0-g01c0d8aa
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 11
Diverged: False
2024-04-02 03:06:21,041 [base_deploy.py:log_info()] - Git Repo klipper-macros: Channel: dev
2024-04-02 03:06:21,041 [base_deploy.py:log_info()] - Git Repo klipper-macros: Validity check for git repo passed
2024-04-02 15:32:55,790 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:32:55,795 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:33:05,807 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:33:35,842 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:33:35,845 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:34:15,888 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:34:15,890 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:34:35,915 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:35:15,962 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:35:15,965 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:36:11,329 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-04-02 15:36:12,366 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0xe7d9cb68>, <Task finished name='Task-4198393' coro=<_HTTPConnection.run() done, defined at /home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=gaierror(-3, 'Temporary failure in name resolution')>)
Traceback (most recent call last):
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 265, in connect
    addrinfo = await self.resolver.resolve(host, port, af)
  File "/home/Pi/moonraker-env/lib/python3.9/site-packages/tornado/netutil.py", line 433, in resolve
    for fam, _, _, _, address in await asyncio.get_running_loop().getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
2024-04-02 15:36:13,352 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-04-02 15:36:15,382 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2024-04-02 15:36:16,045 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:36:16,047 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:36:36,067 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:37:06,099 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:37:36,139 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:37:36,142 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:38:16,189 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:38:16,192 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:38:46,226 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:39:06,259 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:39:16,267 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:39:16,270 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:39:26,282 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:39:26,284 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:39:36,291 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:39:46,302 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:39:46,305 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:40:16,336 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:40:16,338 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:41:36,438 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:41:46,448 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:41:46,450 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:42:16,494 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:42:16,496 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:42:36,521 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:42:36,524 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:44:16,648 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:44:16,650 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:44:26,660 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:45:36,756 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:45:46,766 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:45:46,769 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:46:16,791 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:46:16,792 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:46:36,825 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:46:36,831 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:46:46,833 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:46:46,835 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:46:56,852 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:46:56,855 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:48:16,954 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:48:16,956 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:48:26,963 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:48:36,977 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:48:36,980 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:49:07,016 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:49:07,018 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:49:37,056 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:49:57,070 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:49:57,073 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:50:17,101 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:50:17,103 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:50:37,128 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:51:07,158 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:52:37,244 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:52:47,251 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:52:47,255 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:53:07,271 [machine.py:_find_public_ip()] - Failed to detect local IP address
2024-04-02 15:53:07,273 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2024-04-02 15:53:17,282 [machine.py:_find_public_ip()] - Detected Local IP: 169.254.96.46
2024-04-02 15:53:17,285 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://169.254.96.46
2024-04-02 15:55:17,411 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.18
2024-04-02 15:55:17,414 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.18
2024-04-02 18:17:06,886 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2024-04-02 18:17:06,893 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1712096196.859198, Usage: 1.25%, Memory: 28852 kB
System Time: 1712096197.860289, Usage: 1.23%, Memory: 28852 kB
System Time: 1712096198.862397, Usage: 3.27%, Memory: 28852 kB
System Time: 1712096199.862387, Usage: 1.33%, Memory: 28852 kB
System Time: 1712096200.862693, Usage: 1.28%, Memory: 28852 kB
System Time: 1712096201.863428, Usage: 1.22%, Memory: 28852 kB
System Time: 1712096202.864352, Usage: 1.29%, Memory: 28852 kB
System Time: 1712096203.864967, Usage: 1.21%, Memory: 28852 kB
System Time: 1712096204.866147, Usage: 1.28%, Memory: 28852 kB
System Time: 1712096205.867196, Usage: 1.22%, Memory: 28852 kB
System Time: 1712096206.868208, Usage: 1.28%, Memory: 28852 kB
System Time: 1712096207.870391, Usage: 1.21%, Memory: 28852 kB
System Time: 1712096208.872663, Usage: 3.28%, Memory: 28852 kB
System Time: 1712096209.872953, Usage: 1.34%, Memory: 28852 kB
System Time: 1712096210.874009, Usage: 1.28%, Memory: 28852 kB
System Time: 1712096211.874626, Usage: 1.24%, Memory: 28852 kB
System Time: 1712096212.875163, Usage: 1.25%, Memory: 28852 kB
System Time: 1712096213.877472, Usage: 1.24%, Memory: 28852 kB
System Time: 1712096214.879578, Usage: 1.24%, Memory: 28852 kB
System Time: 1712096215.880404, Usage: 1.23%, Memory: 28852 kB
System Time: 1712096216.881041, Usage: 1.29%, Memory: 28852 kB
System Time: 1712096217.881647, Usage: 1.23%, Memory: 28852 kB
System Time: 1712096218.884135, Usage: 3.3%, Memory: 28852 kB
System Time: 1712096219.884434, Usage: 1.32%, Memory: 28852 kB
System Time: 1712096220.885245, Usage: 1.29%, Memory: 28852 kB
System Time: 1712096221.887671, Usage: 1.2%, Memory: 28852 kB
System Time: 1712096222.888698, Usage: 1.27%, Memory: 28852 kB
System Time: 1712096223.889669, Usage: 1.21%, Memory: 28852 kB
System Time: 1712096224.890349, Usage: 1.25%, Memory: 28852 kB
System Time: 1712096225.891117, Usage: 1.19%, Memory: 28852 kB
CPU Temperature: 48.686
2024-04-02 18:17:06,897 [proc_stats.py:_handle_shutdown()] - Throttled Flags: 
